import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

// todo : 여기 수정해야함.
export const metadata: Metadata = {
  title: "홉지 - 당신이 원한 상품 보기",
  description: "Generated by 유튜버",
  icons: {
    icon: "/hopzie_logo.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
